project_id = "nydtfckvvslkbyolipsf"

[functions.pixup]
verify_jwt = false

[functions.pixup-webhook]
verify_jwt = false

[functions.register]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.send-email]
verify_jwt = false
