project_id = "nydtfckvvslkbyolipsf"

[functions.pixup]
verify_jwt = false

[functions.pixup-webhook]
verify_jwt = false

[functions.register]
verify_jwt = false

[functions.send-email]
verify_jwt = false