project_id = "nydtfckvvslkbyolipsf"

[functions.pixup]
verify_jwt = false

[functions.pixup-webhook]
verify_jwt = false

[functions.evopay]
verify_jwt = false

[functions.evopay-webhook]
verify_jwt = false

[functions.register]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.cleanup-expired-orders]
verify_jwt = false

[functions.expire-subscriptions]
verify_jwt = false

[functions.sync-sessions-inventory]
verify_jwt = false

[functions.cleanup-expired-reservations]
verify_jwt = false

[functions.create-payment-with-fallback]
verify_jwt = false
